Output examples/demo.gif

Set WindowBar Colorful
Set FontSize 14
Set Width 1028
Set Height 640
Set TypingSpeed 0.1

Hide
Type "go build ."
Enter
Type "go install"
Enter
Require initiative
Type "clear"
Enter
Show

Type "initiative"
Enter
Sleep 2

# Adding characters

Tab
Sleep 2

Type "n"
Type "Shadowheart"
Enter
Sleep 1

# Added Shadowheart

Type "n"
Type "Gale"
Enter
Sleep 1

# Added Gale

Type "n"
Type "Astarion"
Enter
Sleep 1

# Added Astarion

Type "n"
Type "Wyll"
Enter
Sleep 1

# Added Wyll

Type "n"
Type "Minthara"
Enter

# Added Minthara

# Deleting a character (Astarion)

Sleep 1
Down 3
Sleep 2
Type "d"
Sleep 3

# Switching to encounter tab and creating new encounter

Shift+Tab
Sleep 3
Type "n"

# Providing the summary

Type "Defending the Emerald Grove"
Sleep 2
Enter

# Keeping all characters selected

Sleep 2
Enter

# Filter SRD monsters and select goblins, hobgoblins, and 

Sleep 2
Type "/goblin"
Ctrl+A
Sleep 2

Delete 6
Type "bu"
Escape
Sleep 2
Space
Sleep 1
Enter

# Set quantities of each monster (bugbear, goblin, hobgoblin)

Sleep 1
Backspace
Type "2"
Enter
Sleep 1
Type "2" # for a total of 12
Enter
Sleep 1
Backspace
Type "4"
Enter
Sleep 1

# Set initiative (bugbear, goblin, hobgoblin)

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

Type "7"
Enter
Sleep 1

# Encounter has started

Right 8